global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "market-data"
    static_configs:
      - targets: ["market-data:7001"]

  - job_name: "strategy-engine"
    static_configs:
      - targets: ["strategy-engine:7002"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "market-data"
    static_configs:
      - targets: ["market-data:7001"]

  - job_name: "strategy-engine"
    static_configs:
      - targets: ["strategy-engine:7002"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
